// Preserve the pre-refactor CSS cascade; change this order only with visual verification.
import '../components/legacySources.css'
import '../components/simple-chart-axes.css'
import '../pages/devices/acquisition.css'
import '../pages/dispersion/dispersion.css'
import '../pages/acquisition/sample-acquisition.css'
import '../pages/hardwareAcquisition/hardware-acquisition.css'
import '../pages/mercuryCalibration/mercury-calibration.css'
import '../pages/analysis/analysis.css'
import '../pages/postprocessing/postprocessing.css'
import './global.css'
import '../pages/methods/methods.css'
import '../pages/migration/migration.css'
import '../pages/sampleQueues/sample-queue.css'
import '../pages/spectra/spectrum-viewer.css'
import './visual-refinement.css'
import './remaining-pages.css'
