"""Analysis operations needed by exact-version postprocessing."""

from typing import Any, Protocol


class RecalculationAnalysis(Protocol):
    def curve_evaluators(self, snapshot_ids: list[int], method_version_id: int, calculation_profile: str) -> dict[str, dict[str, Any]]: ...
    def create_run(self, payload: dict[str, Any], actor_user_id: int | None = None) -> dict[str, Any]: ...
    def start(self, run_id: int, actor_user_id: int | None = None) -> dict[str, Any]: ...
    def step(self, run_id: int, actor_user_id: int | None = None) -> dict[str, Any]: ...
